openapi: 3.1.0
info:
  title: Marketing Automation API Reference
  version: '1.0'
  summary: API
servers:
  - url: 'https://app.vessel.dev/api'
security:
  - VesselAPIToken: []
paths:
  /api/unifications/marketing/users/list:
    post:
      summary: List Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    users:
                      - id: e5f32d4fd2115220bd20a2ccf81210ec
                        email: tom@dundermifflin.com
                        firstName: Tom
                        lastName: Haverford
                        createdTime: '2019-08-24T14:15:22Z'
                        modifiedTime: '2019-08-24T14:15:22Z'
                    nextPageCursor: '123123'
      parameters:
        - name: x-vessel-access-token
          in: header
          description: Access Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cursor:
                  type: string
            examples:
              example-1:
                value:
                  cursor: '123123'
      operationId: get-all-users
      description: List Users
    parameters: []
  /api/unifications/marketing/contacts/list:
    post:
      summary: List Contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    contacts:
                      - id: e5f32d4fd2115220bd20a2ccf81210ec
                        email: tom@dundermifflin.com
                        firstName: Tom
                        lastName: Haverford
                        phone: '8192223333'
                        createdTime: '2019-08-24T14:15:22Z'
                        modifiedTime: '2019-08-24T14:15:22Z'
                    nextPageCursor: '123123'
      parameters:
        - name: x-vessel-access-token
          in: header
          description: Access Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cursor:
                  type: string
            examples:
              example-1:
                value:
                  cursor: '123123'
      operationId: get-all-contacts
      description: List Contacts
    parameters: []
  /api/unifications/marketing/contacts/find:
    post:
      summary: Find Contact
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  contact:
                    $ref: '#/components/schemas/Contact'
              examples:
                example-1:
                  value:
                    contact:
                      id: e5f32d4fd2115220bd20a2ccf81210ec
                      email: tom@dundermifflin.com
                      firstName: Tom
                      lastName: Haverford
                      phone: '8192223333'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
      parameters:
        - name: x-vessel-access-token
          in: header
          description: Access Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
            examples:
              example-1:
                value:
                  id: '123123'
      operationId: get-one-contact
      description: Find Contact
    parameters: []
  /api/unifications/marketing/contacts/create:
    post:
      summary: Create Contact
      operationId: post-contact
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  id:
                    type: string
              examples:
                example-1:
                  value:
                    id: '0'
      parameters:
        - name: x-vessel-access-token
          in: header
          description: Access Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  $ref: '#/components/schemas/ContactCreate'
              required:
                - contact
            examples:
              example-1:
                value:
                  contact:
                    email: tom@dundermifflin.com
                    firstName: Tom
                    lastName: Haverford
                    phone: '8192223333'
                    listId: '12'
      description: Create a Contact
  /api/unifications/marketing/contacts/update:
    post:
      summary: Update Contact
      operationId: put-contact
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: '0'
                properties:
                  id:
                    type: string
                required:
                  - id
              examples:
                example-1:
                  value:
                    id: '0'
      parameters:
        - name: x-vessel-access-token
          in: header
          description: Access Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                contact:
                  $ref: '#/components/schemas/ContactUpdate'
              required:
                - id
                - contact
            examples:
              example-1:
                value:
                  id: string
                  contact:
                    email: tom@dundermifflin.com
                    firstName: Tom
                    lastName: Haverford
                    phone: '8192223333'
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      description: Update an existing Contact
    parameters: []
  /api/unifications/marketing/lists/list:
    post:
      summary: List Lists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  lists:
                    type: array
                    items:
                      $ref: '#/components/schemas/List'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    lists:
                      - id: e5f32d4fd2115220bd20a2ccf81210ec
                        name: 'Paper leads'
                        createdTime: '2019-08-24T14:15:22Z'
                        modifiedTime: '2019-08-24T14:15:22Z'
                    nextPageCursor: '123123'
      parameters:
        - name: x-vessel-access-token
          in: header
          description: Access Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cursor:
                  type: string
            examples:
              example-1:
                value:
                  cursor: '123123'
      operationId: get-all-lists
      description: List Lists
    parameters: []
  /api/unifications/marketing/lists/find:
    post:
      summary: Find List
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  list:
                    $ref: '#/components/schemas/List'
              examples:
                example-1:
                  value:
                    list:
                      id: e5f32d4fd2115220bd20a2ccf81210ec
                      name: 'Paper leads'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
      parameters:
        - name: x-vessel-access-token
          in: header
          description: Access Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
            examples:
              example-1:
                value:
                  id: '123123'
      operationId: get-one-list
      description: Find List
    parameters: []
  /api/passthrough/marketing:
    post:
      summary: Passthrough Request
      operationId: passthrough
      parameters:
      - name: x-vessel-access-token
        in: header
        description: Access Token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ''
                type: object
                properties:
                  headers:
                    type: object
                  url:
                    type: string
                    description: The full URL that the request was sent to.
                  statusCode:
                    type: number
                    description: The HTTP status code of the response from the downstream system.
                  body:
                    AnyValue:
                      description: The body of the response from the downstream system.
                required:
                  - id
              examples:
                example-1:
                  value:
                    headers:
                      content-type: application/json
                    url: https://sometool.com/api/v1/endpoint
                    statusCode: 200
                    body:
                      id: 123123123123
                      success: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                method:
                  type: string
                  enum:
                    - GET
                    - POST
                    - PUT
                    - PATCH
                    - DELETE
                path:
                  type: string
                  description: "The path to send the request to. Vessel handles the domain, for example, a request to Salesforce would use 'services/data/v52.0/sobjects/Account' instead of 'https://mydomain.my.salesforce.com/services/data/v52.0/sobjects/Account'."
                body:
                  type: object
                  description: 'The body of the request.'
                query:
                  type: object
                  description: 'The query parameters to send with the request as key value pairs. These are appended to the URL when the request is sent to the integration provider.'
              required:
                - method
                - path
            examples:
              example-1:
                value:
                  method: PATCH
                  path: services/data/v53.0/sobjects/Account/0011A00001XQ4ZUQA1
                  body:
                    - Name: 'Vessel'
        description: ''
      description: Send an authenticated passthrough request to the downstream system. This is useful for making requests to endpoints that are not yet supported by Vessel.
components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - id: e5f32d4fd2115220bd20a2ccf81210ec
          email: tom@dundermifflin.com
          firstName: Tom
          lastName: Haverford
          createdTime: '2019-08-24T14:15:22Z'
          modifiedTime: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: string
          description: Id of the object in the connected Marketing tool.
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        createdTime:
          type: string
          description: The timestamp that the user was created
        modifiedTime:
          type: string
          description: The timestamp the user was last modified
      required:
        - id
        - createdTime
        - modifiedTime
    Contact:
      title: Contact
      type: object
      examples:
        - id: e5f32d4fd2115220bd20a2ccf81210ec
          email: tom@dundermifflin.com
          firstName: Tom
          lastName: Haverford
          phone: '8192223333'
          createdTime: '2019-08-24T14:15:22Z'
          modifiedTime: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: string
          description: Id of the object in the connected Marketing tool.
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        createdTime:
          type: string
          description: The timestamp that the contact was created
        modifiedTime:
          type: string
          description: The timestamp the contact was last modified
      required:
        - id
        - createdTime
        - modifiedTime
    ContactCreate:
      title: ContactCreate
      type: object
      examples:
        - email: tom@dundermifflin.com
          firstName: Tom
          lastName: Haverford
          phone: '8192223333'
          listId: '12'
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        listId:
          type: string
    ContactUpdate:
      title: ContactUpdate
      type: object
      examples:
        - id: e5f32d4fd2115220bd20a2ccf81210ec
          email: tom@dundermifflin.com
          firstName: Tom
          lastName: Haverford
          phone: '8192223333'
      properties:
        id:
          type: string
          description: Id of the object in the connected Marketing tool.
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
      required:
        - id
        - createdTime
        - modifiedTime
    List:
      title: List
      type: object
      examples:
        - id: e5f32d4fd2115220bd20a2ccf81210ec
          name: 'Paper leads'
          createdTime: '2019-08-24T14:15:22Z'
          modifiedTime: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: string
          description: Id of the object in the connected Marketing tool.
        name:
          type: string
        createdTime:
          type: string
          description: The timestamp that the list was created
        modifiedTime:
          type: string
          description: The timestamp the list was last modified
      required:
        - id
        - createdTime
        - modifiedTime
  securitySchemes:
    VesselAPIToken:
      name: x-vessel-api-token
      type: apiKey
      in: header
